### ISSUE TITLE
Trying Latest commit f8cc074 - many errors..

### ISSUE THREAD

**Issue by blondie63** [mdbootstrap/Angular-Bootstrap-Boilerplate#2]
Are you sure this code is working ?
I've downloaded and run npm i, this is my log:
[2019-07-02T10_31_23_452Z-debug.log](https://github.com/mdbootstrap/Angular-Bootstrap-Boilerplate/files/3351069/2019-07-02T10_31_23_452Z-debug.log)

**Comment by idzark** [comment]
You are probably using node >12 and/or Angular 8. The boilerplate is not updated to new Angular version yet.

**Comment by idzark** [comment]
The boilerplate is now ready to use with Angular 8
