### ISSUE TITLE
@ngrx/core@1.2.0

### ISSUE THREAD

**Issue by blondie63** [mdbootstrap/Angular-Bootstrap-Boilerplate#3]
How to solve this warning:
npm WARN @ngrx/core@1.2.0 requires a peer of rxjs@^5.0.0-beta.12 but none is installed. You must install peer dependencies yourself.

**Comment by idzark** [comment]
Please ignore this warning for now if everything is working correctly in the boilerplate. We need to update ngrx version.

**Comment by idzark** [comment]
We updated NgRx version in the v8.1.0 of the boilerplate. You will no longer see the warnings after update. 

If you don't want to update the boilerplate files, you can just remove the @ngrx/core package from your package.json.
